### PR TITLE
Add setting to represent languages as labels instead of flags in backend.

### PR DESCRIPTION
**Pull request by hatsumatsu**
This is a rough PR for adding text based language labels in the WP backend. To test this feature go to _Settings_ > _Multisite Language Switcher_ and set _Admin Display_ to _Labels_.

The labels are displayed in post lists, post edit screens and in the admin bar. See attached screenshot. 

Screenshot 2020-06-30 at 11 16 46

### CODE REVIEW

**Comment by Idealien** [comment]
@lloc - Both this PR and #150 are trying to address a common goal where the default country/flag doesn't fit.

Examples include:
- The en_CA and fr_CA flag are identical.
- A network has multiple pairs of sites (10 sites = 5 actual sites x 2 language each) and having the identical flag for selector.

Would be good to know if these approaches are enhancements likely to be considered?

**Comment by lloc** [comment]
I agree that this is probably the way to go ... I'd like to be sure that the user can choose which solution is the best for his/her needs. I did not check this but I will do this as fast as possible.

**Comment by Idealien** [comment]
> I did not check this but I will do this as fast as possible.

Thanks. Running a fork with PR150 in some environments until the chosen/preferred approach gets implemented. Would love to be able to return back to master with WP 5.8+ if that kind of time frame is realistic for one or other to be part of plugin updates?

**Comment by hatsumatsu** [comment]
Hi @lloc , no pressure, but just curious if you consider this PR to be a good idea and potentially being merged? Would love to see this feature in the official version of the plugin :-)

**Pull request merged**
