### PR TITLE
Ability to filter supported post types and arabic flag fixes

### PR DESCRIPTION
**Pull request by matthewsuan**
Right now, switcher is only available for public post types. There are non-public post types that needs MSLS feature too. So this filter will take care of that.

```
add_filter('msls_supported_post_types', function($types) {
    $nonPublicPostType = 'faq'; // suppose faq is registered as not public
    $types[] = $nonPublicPostType; 
    return $types;
});
```

### CODE REVIEW

**Comment by matthewsuan** [comment]
@lloc trying to see if this can be merged in the near future? Let me know how can I help too

**Comment by lloc** [comment]
Hey Matthew,

thanks for helping here. I'd like to split these PRs ... the filter seems reasonable.

The fix for the Arabic flag is probably ok. Where does the image come from?

Cheers!

**Comment by matthewsuan** [comment]
Thanks @lloc 

The image is coming from the same folder. ae.png

**Comment by matthewsuan** [comment]
I'm sorry. its coming from the arableague.png file on the same folder.

**Comment by lloc** [comment]
OK thanks for the PR

**Pull request merged**
