### PR TITLE
Update metabox listing script

### PR DESCRIPTION
**Pull request by smoothstepdesign**
Upgraded the metabox list script to remove the need of creating post object for each list item.

### CODE REVIEW

**Comment by smoothstepdesign** [comment]
The first update was incomplete but I was unable to modify it further, had to correct it with the second update.

**Comment by lloc** [comment]
Please follow the WordPress Coding Standards next time ;)

**Comment by smoothstepdesign** [comment]
Well in this case the problem is with Wordpress coding standards. There is some kind of problem in Wordpress core and/or probably in the PHP itself that creates memory leakage when creating post object and your plugin fails with ~1000 posts. With my update it works fine with 2500+ posts.

**Comment by lloc** [comment]
I allready corrected these small things ... it was just a hint for the next time. ;) And BTW it has just to do with the way how we have to write code for WordPress. 

All this has nothing to do with the WordPress core but with the old (soon deprecated) way to show posts in a html select. Please have also a look here: https://scrutinizer-ci.com/g/lloc/Multisite-Language-Switcher/inspections/24dcf02d-4c66-4403-b766-5a5d2f43a816/code-structure/operation/%2Bglobal%5CMslsMetaBox%3A%3Arender_select

**Comment by smoothstepdesign** [comment]
Well what I meant is that this code while suggested by Wordpress is very inefficient, consumes too much RAM:

-					while ( $my_query->have_posts() ) {
-						$my_query->the_post();
-						$my_id    = get_the_ID();
-						$title = get_the_title();

What should happen that the Wordpress Query class should pull all the titles from the database using a single SQL query and then get_the_title() should prepare the title with little extra memory. However its not how it works, if 1000+ posts are present it consumes over 256MB of RAM, also becomes slow and unstable. I was looking at Wordpress source code and it seams that $my_query->the_post() creates Post object and then within get_the_title() function the object is created again. Since PHP memory handling is not perfect somehow this second Post object is not disposed of and insane amounts of memory are consumed.

To resume it - their code works relatively well when only a few posts are listed but as post count becomes larger their approach becomes very inefficient. There are many more of these issues with Wordpress hopefully they will be addressed one day.

**Pull request merged**
