### PR TITLE
Update MslsOutput.php

### PR DESCRIPTION
**Pull request by jacksoggetto**
added mlsl_output_hreflang filter

I was thinking about somthing like this, of course you have the last word, and I don't mind you changing the code, in fact I encourage you to make it better since you are definitely way better than me at programming

### CODE REVIEW

**Comment by lloc** [comment]
I believe there is additional stuff to solve (line 124 leads to a mixed type because $default is a string and $arr should be an array). I think there should be also a filter for the default var.

What do you think if you'd to try something like this: 

`if ( 1 === count( $arr ) ) {
    return apply_filters( 'mlsl_output_get_alternate_links_default', $default );
}

$arr = (array) apply_filters( 'mlsl_output_get_alternate_links_arr', $arr );

return implode( PHP_EOL,  $arr );`

**Comment by jacksoggetto** [comment]
It's way better than my version. I'm really happy with this (as I said in another comment I as trusting you being a better coder than me, I'm not that good honestly)

I'll be honest, the main reason I told you to make this edit is this:
watching at what some well done websites are doing, and reading online this should be the hreflang behaviour:
if no tranlations, no hreflang
if transalation, add an x-default to the main language (so if I have italian and english, someone searching in french is sent to the x-default version

but with this solutions it requires a filter to make any type of change, so it seems perfect to me, as everyone will be able to manipulate the output

**Comment by jacksoggetto** [comment]
Ok, hope I did that correctly

**Comment by lloc** [comment]
Closed in favour of #187

**Comment by lloc** [comment]
Thanks for contributing! :100:

**Pull request closed without merging**
